# LLM Configuration
llm:
  provider: "openai"  # or "gemini"
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-3.5-turbo"
    embedding_model: "text-embedding-ada-002"
    embedding_dimension: 1536  # OpenAI text-embedding-ada-002 dimension
    timeout: 30
  gemini:
    api_key: "${GEMINI_API_KEY}"
    model: "gemini-pro"
    timeout: 30

# ChromaDB Configuration
database:
  persist_directory: "/app/data/chromadb"
  collection_name: "inventory"
  embedding_dimension: 1536  # Must match LLM embedding dimension
  
# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 1.0
  fallback_to_cloud: true
  
# Transaction Settings
transactions:
  bulk_timeout: 300
  max_bulk_size: 100

# Voice Configuration
voice:
  # Voice provider: "browser" (free, fast) or "openai" (premium quality)
  provider: "openai"

  # Browser voice settings (used when provider = "browser")
  browser:
    tts_rate: 0.9
    tts_pitch: 1.0
    tts_volume: 0.8

  # OpenAI voice settings (used when provider = "openai")
  openai:
    tts_model: "tts-1"  # or "tts-1-hd" for higher quality
    tts_voice: "alloy"  # alloy, echo, fable, onyx, nova, shimmer
    whisper_model: "whisper-1"
    audio_format: "opus"  # opus is faster to encode/decode than mp3

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
