# LLM Configuration
llm:
  provider: "openai"  # or "gemini"
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-3.5-turbo"
    embedding_model: "text-embedding-ada-002"
    timeout: 30
  gemini:
    api_key: "${GEMINI_API_KEY}"
    model: "gemini-pro"
    timeout: 30

# ChromaDB Configuration  
database:
  persist_directory: "/app/data/chromadb"
  collection_name: "inventory"
  
# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 1.0
  fallback_to_cloud: true
  
# Transaction Settings
transactions:
  bulk_timeout: 300
  max_bulk_size: 100

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
